#!/usr/bin/env python3

import os
import subprocess
import signal
import sys


EXAMPLES = {
    "1": "guessing_game",
}


def main():
    choice = sys.argv[1] if len(sys.argv) > 1 else 0
    if choice not in list(EXAMPLES.keys()):
        print("[!] Select a valid choice.")
        sys.exit(-1)
    
    print("[+] Running example {}".format(EXAMPLES[choice]))

    try:
        path = "{}/{}/Cargo.toml".format(os.getcwd(), EXAMPLES[choice])
        process = subprocess.run(["cargo", "run", "--manifest-path", path])
    except KeyboardInterrupt:
        print("[!] Exiting...")
        sys.exit(0)

if __name__ == "__main__":
    main()
